#!/bin/bash

command=$1

if [ "$command" = "init" ]; then
    TERRAFORM_DIR="./provisioning"

    echo "Initializing Terraform..."
    terraform -chdir="$TERRAFORM_DIR" init
   
    echo "Applying Terraform..."
    terraform -chdir="$TERRAFORM_DIR" apply -auto-approve
    ansible-playbook ./playbooks/efs.yml
fi

if [ "$command" = "start" ]; then
    TERRAFORM_DIR="./provisioning"

    echo "Initializing Terraform..."
    terraform -chdir="$TERRAFORM_DIR" init
   
    echo "Applying Terraform..."
    terraform -chdir="$TERRAFORM_DIR" apply -auto-approve

    ansible-playbook ./playbooks/efs.yml

    ansible-playbook ./playbooks/tekton.yml
    ansible-playbook ./playbooks/tekton-resource.yml 
    ansible-playbook ./playbooks/argocd.yml
    ansible-playbook ./playbooks/argocd-resource.yml
fi

if [ "$command" = "add" ]; then
    ansible-playbook ./playbooks/tekton-resource.yml 
    ansible-playbook ./playbooks/argocd-resource.yml
fi

if [ "$command" = "tekton" ]; then
    ansible-playbook ./playbooks/tekton.yml 
    ansible-playbook ./playbooks/tekton-resource.yml 
fi

if [ "$command" = "argocd" ]; then
    ansible-playbook ./playbooks/argocd.yml
    ansible-playbook ./playbooks/argocd-resource.yml
fi
