apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: default
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.gitSecret.username }}
  password: {{ .Values.gitSecret.password }} # github에서 토큰을 만들어서 가져와야됨
---
apiVersion: v1
kind: Secret
metadata:
 name: docker-credential
 namespace: default
type: kubernetes.io/dockerconfigjson 
data:
  .dockerconfigjson: {{ .Values.docker.configJson }} 

