gitSecret:
  username: "jalju0804"
  password: "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"
docker:
  configJson: "ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJICJhdXRoIjogIlpHeGphM04zYmpNek5EcHNaV1ZqYWpBNE1EUWgiCgkJfQoJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiCn0K"
efsID: "fs-0c43458ac9da838f4"
