apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gcd-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jalju0804/gcd-manifest.git
    targetRevision: HEAD
    path: backend/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
