---
- name: Conditional Tekton Helm Installation
  hosts: localhost
  vars_files:
    - gcd.yml

  tasks:
    - name: Pause for a few seconds
      pause:
        seconds: 10

    - name: FileSystemId Print
      command:
        cmd: aws efs describe-file-systems
      register: efs_describe

    - name: FileSystemId export
      set_fact:
        filesystem_id: "{{ (efs_describe.stdout | from_json).FileSystems[0].FileSystemId }}"

    - name: Generate YAML file from variables
      copy:
        content: |
          gitSecret:
            username: "{{ gitSecret.username }}"
            password: "{{ gitSecret.password }}"
          docker:
            configJson: "{{ docker.configJson }}"
          efsID: "{{ filesystem_id }}"
        dest: "../helm/tekton-resource/values.yaml"

    - block:
        - name: Install Tekton Helm
          command:
            cmd: helm install tekton ../helm/tekton
          register: helm_tekton_output

        - name: Print Helm Tekton Output
          debug:
            msg: "{{ helm_tekton_output.stdout_lines }}"

        - name: Wait for all Tekton pods to be running
          command:
            cmd: kubectl get pods -n tekton-pipelines --field-selector=status.phase!=Running
          register: get_pods
          until: get_pods.stdout == ""
          retries: 30
          delay: 30

        - name: Install Tekton resource
          command:
            cmd: helm install tekton-resource ../helm/tekton-resource
          register: helm_install_output

        - name: Print Helm Install Output
          debug:
            msg: "{{ helm_install_output.stdout_lines }}"

        - name: Pause for a few seconds
          pause:
            seconds: 10

        - name: install tekton polling crd
          command:
            cmd: kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.14.2/release.yaml
          register: install_tekton_polling_crd
          ignore_errors: yes

        - name: Print install tekton polling crd
          debug:
            msg: "{{install_tekton_polling_crd}}"
            
        - name: Pause for a few seconds
          pause:
            seconds: 10
            
        - name: install tekton polling operator
          command:
            cmd: kubectl apply -f https://github.com/bigkevmcd/tekton-polling-operator/releases/download/v0.4.0/release-v0.4.0.yaml
          register: install_tekton_polling_operator

        - name: Print install tekton polling operator
          debug:
            msg: "{{install_tekton_polling_operator}}"
            
        - name: Pause for a few seconds
          pause:
            seconds: 30

      rescue:
        - name: Print Error Message
          debug:
            msg: "Tekton Helm installation failed"
